version: '3'
services:
  web:
    build: .
    ports:
     - "5000:3000"
    volumes:
      - ".:/app"
    command: bash -c "bin/rake assets:precompile && bin/rake db:create && bin/rake db:migrate && bin/rails s"

volumes:
  data: {}
